stages:
  - test

test:
  stage: test
  image: node:20
  before_script:
    - npm ci
  script:
    - npm run check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
